export const urlBase = "https://proyectou8-production.up.railway.app/api/v1/"
export const urlUser = "https://proyectou8-production.up.railway.app/api/v1/user"
export const urlPet = "https://proyectou8-production.up.railway.app/api/v1/pet"
export const urlPetDiagnostic = "https://proyectou8-production.up.railway.app/api/v1/pet-diagnostic"
export const urlAdoption = "https://proyectou8-production.up.railway.app/api/v1/pet-adoption"
export const urlApplication =  "https://proyectou8-production.up.railway.app/api/v1/application"